# docker-compose.yml
version: "3.8"

services:
  peer:
    build: ./chat
    ports:
      - "5000"
    environment:
      - PORTA_RECEBIMENTO=5000
    volumes:
      - logs-volume:/logs
    networks:
      - chatmesh-net

  web:
    build: ./web
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_PORT=8000
      - PEER_DESTINO=peer:5000
      - PEER_NAME=Peer-Web
    volumes:
      - logs-volume:/logs
    networks:
      - chatmesh-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  logs-volume:

networks:
  chatmesh-net:
    driver: bridge
