version: "3.8"

services:
  peer:
    build: ./chat
    environment:
      - PORTA_RECEBIMENTO=5000
    networks:
      - chatmesh-net
    volumes:
      - logs-volume:/logs

  web:
    build: ./web
    ports:
      - "8000:8000"
    networks:
      - chatmesh-net
    volumes:
      - logs-volume:/logs
    command: uvicorn main:app --host 0.0.0.0 --port 8000

networks:
  chatmesh-net:
    driver: bridge

volumes:
  logs-volume:
