version: "3.8"

services:
  peer1:
    build: ./chat
    container_name: peer1
    environment:
      - PORTA_RECEBIMENTO=5000
      - PEERS_CONHECIDOS=peer2:5001
      - NOME_PEER=Peer1
      - INTERVALO_ENVIO=5
    ports:
      - "5000:5000"
    networks:
      - chatmesh-net
    volumes:
      - logs-volume:/logs

  peer2:
    build: ./chat
    container_name: peer2
    environment:
      - PORTA_RECEBIMENTO=5001
      - PEERS_CONHECIDOS=peer1:5000
      - NOME_PEER=Peer2
      - INTERVALO_ENVIO=5
    ports:
      - "5001:5001"
    networks:
      - chatmesh-net
    volumes:
      - logs-volume:/logs

networks:
  chatmesh-net:
    driver: bridge

volumes:
  logs-volume:
