version: "3.8"

services:
  peer:
    build: ./chat
    environment:
      - PORTA_RECEBIMENTO=5000
    volumes:
      - logs-volume:/logs
    networks:
      - chatmesh-net
    deploy:
      mode: replicated
      replicas: 1 # NÃO escalar aqui, vamos usar --scale manual

  web:
    build: ./web
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - logs-volume:/logs
    networks:
      - chatmesh-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  logs-volume:

networks:
  chatmesh-net:
    driver: bridge
